### ISSUE TITLE
Uncaught Error: Pane has been destroyed

### ISSUE THREAD

**Issue by ZachTRice** [atom/notifications#127]
[Enter steps to reproduce below:]

1. Used command to split panes. 2 split panes open; 1 left and 1 right.  
2. Closed all tabs in the left pane. At which time the pane did not auto-close and slide over, as usual. 3. Closed panes in the right pane. Both panes stayed visible; at which time error appeared.

I used the following keymap to initially split the panes:
    '.platform-win32':
      'alt-shift-2': 'pane:split-right'

I did not have the error occur again throughout the day and I am not currently able to replicate the error on another Windows machine. 

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Pro
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.63.1

### Stack Trace

Uncaught Error: Pane has been destroyed

```
At C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:804

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:804:15)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:248:19)
    at C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\src\notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (C:\Users\WoodST\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\notifications\lib\notification-element.js:147:26)
```

### Commands

```
  2x -0:18.9.0 pane:close (div.item-views)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monocolor-light-blue-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.5.2
aligner, v0.22.0
aligner-css, v1.2.0
aligner-php, v1.0.0
atom-beautify, v0.29.8
atomic-chrome, v0.3.0
autocomplete-wordpress-hooks, v0.2.0
bottom-dock, v0.4.4
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.14
git-plus, v5.15.0
highlight-selected, v0.11.2
irregular-keypress-sounds, v0.2.0
language-blade, v0.25.3
less-than-slash, v0.13.0
linter, v1.11.8
linter-csslint, v1.3.2
linter-jshint, v2.1.0
linter-jsonlint, v1.2.5
linter-manager, v0.2.12
linter-php, v1.2.0
linter-tidy, v2.1.1
minimap, v4.24.4
minimap-cursorline, v0.2.0
minimap-find-and-replace, v4.5.1
minimap-highlight-selected, v4.4.0
minimap-pigments, v0.2.1
minimap-selection, v4.4.0
minimap-split-diff, v0.3.1
monocolor-light-blue-syntax, v1.0.0
php-cs-fixer, v2.5.6
pigments, v0.29.2
Remote-FTP, v0.8.3
sync-settings, v0.7.2

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
@ZachTRice What were you doing when this happened?

**Comment by ZachTRice** [comment]
@50Wliu Steps to reproduce the issue have been added.

**Comment by 50Wliu** [comment]
Ok.  Based on your reproduction steps I _believe_ that this issue should be fixed in Atom 1.9.0.

**Comment by danielandrews** [comment]
Still seeing this in `1.10.2`:


-------------------------------------------

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [notifications](https://github.com/atom/notifications) package, v0.65.0


### Stack Trace

Uncaught Error: Pane has been destroyed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:828

Error: Pane has been destroyed
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:828:15)
    at atom-notification.NotificationElement.removeNotificationAfterTimeout (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:290:40)
    at atom-notification.NotificationElement.removeNotification (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:248:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:57:26
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Notification.module.exports.Notification.dismiss (/Applications/Atom.app/Contents/Resources/app.asar/src/notification.js:79:27)
    at atom-notification.NotificationElement.handleRemoveNotificationClick (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:252:25)
    at HTMLDivElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/notifications/lib/notification-element.js:147:26)
```

### Commands

```
  2x -9:37.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -9:36.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -9:07.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:59.7.0 editor:outdent-selected-rows (atom-text-editor.editor.is-focused)
     -8:57.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:56.9.0 core:save (atom-text-editor.editor.is-focused)
  2x -8:50.4.0 core:undo (atom-text-editor.editor.is-focused)
  2x -8:44.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -8:43.1.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:11.4.0 pane:close (div.item-views)
  2x -0:02.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "allowPendingPaneItems": false,
    "disabledPackages": [
      "open-terminal-here",
      "wrap-guide",
      "atom-prettify",
      "csslint",
      "remote-edit",
      "metrics",
      "tool-bar-main",
      "block-cursor",
      "css-color-underline",
      "tool-bar",
      "styleguide",
      "terminal-plus",
      "jshint",
      "autoprefixer"
    ],
    "projectHome": "~/",
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.5 (active)
atom-beautify, v0.29.13 (active)
atom-css-comb, v3.1.0 (inactive)
atom-terminal, v0.8.0 (inactive)
atom-theme-manager, v0.0.6 (active)
autoprefixer, v3.3.0 (inactive)
cobalt2-syntax, v0.4.0 (active)
csscomb, v0.3.1 (inactive)
csslint, v1.1.5 (inactive)
emmet, v2.4.3 (active)
file-icons, v1.7.20 (active)
git-plus, v5.18.0 (active)
highlight-line, v0.11.1 (active)
highlight-selected, v0.11.2 (active)
indent-guide-improved, v1.4.10 (active)
javascript-snippets, v1.2.1 (active)
jshint, v1.8.6 (inactive)
language-slim, v0.5.0 (active)
linter, v1.11.18 (active)
linter-scss-lint, v3.0.4 (active)
linter-tidy, v2.2.0 (active)
merge-conflicts, v1.4.4 (active)
minimap, v4.25.0 (active)
minimap-highlight-selected, v4.4.0 (active)
pigments, v0.37.0 (active)
pinned-tabs, v0.4.1 (active)
project-manager, v3.2.3 (active)
quick-editor, v0.4.3 (inactive)
sort-lines, v0.14.0 (inactive)
sync-settings, v0.7.2 (active)
terminal-plus, v0.14.5 (inactive)
trailing-spaces, v0.3.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (active)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (inactive)
symbols-view, v0.113.0 (active)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (inactive)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by Ben3eeE** [comment]
@danielandrews What were you doing when this happened?

**Comment by alexandrethsilva** [comment]
This has been throwing for me almost every time I close the last tab on a split pane.

**Comment by Ben3eeE** [comment]
@alexandrethsilva Can you please post the full error here with steps to reproduce when this happens? Do you see if if you run Atom in safe mode `atom --safe`?

**Comment by Ben3eeE** [comment]
Also what tabs have you had open in the pane when you get this error? Is there some specific package like an `image-view` tab or `settings-view` tab or only TextEditors? We have been having this error occur with the `settings-view` and `markdown-preview` before.

**Comment by jwithington** [comment]
This happened to me as well, but I didn't grab the stack trace. I had split what I was working on right, and then closed that tab. I think it also had to do with minimap.

**Comment by Ben3eeE** [comment]
* If you get this exception with the `settings-view` open: https://github.com/atom/atom/issues/12498#issuecomment-243669440
* If it happens and you also get an error from `minimap`: https://github.com/atom-minimap/minimap/issues/489#issuecomment-254057876
* If it happens for other reasons: Create a new issue with steps to reproduce and include full stack trace.
